### ISSUE TITLE
[enhancement] アクセストークンを指定するヘッダー名を指定したい

### ISSUE THREAD

**Issue by komuro-hiraku** [cm-kazup0n/aurl-rust#18]
# 概要

取得したアクセストークンはデフォルトでは `Authorization` ヘッダに Bearer トークンとして付与される。
これを指定した任意のヘッダへ変更する機能を検討する。

# 仕様

## IF 案

| オプション | パラメータサンプル | 必須 | 
|:------------|:-------------------|:--------------|
| `--token-header` | `X-AccessToken` | option |

## 動作定義

- `--token-header` オプションに文字列をすることで機能が利用できる
- オプションを指定しない場合は機能は動作しない
- オプションで指定された文字列の最大長（最大長定義はハードコード）を検証する
- 認証フローで取得したトークンを付与して、指定URL へアクセスする際に、オプションで指定された文字列をヘッダとして設定する
- 認証フローで取得したトークンは `Bearer` トークンとする
- オプションを指定しない場合は、 `Authorization` ヘッダにトークンを記述する

# 処理シーケンス

1. アクセストークン取得フロー省略
2. Token Response からアクセストークンを取得
3. オプションが有効な場合、指定された文字列を HTTP ヘッダに追加する
4. 追加したヘッダの値には `Bearer 取得したアクセストークン` の文字列を設定する
5. 指定した URL へアクセスする

# エラー

## 最大長を超えてる

オプションに指定された文字列が最大長を超えた場合、エラーで処理が中断される

**Comment by cm-kazup0n** [comment]
以下の仕様を考慮したい。

## profileで指定したい

アクセストークンを付与するヘッダーは一連のAPI単位（エンドポイントではなくて）で決まっていることが多いと思うので、リクエストごとではなくてプロファイル単位で指定したい。
i.e. 同じプロファイルを使う場合はデフォルトで指定されていて欲しい

## ヘッダーのテンプレート形式で指定した

ヘッダーの値にBearerのようなプリフィクスがある場合、ない場合がある。これらの有無をフラグで指定するのは冗長なので、より広いユースケースに適用するためにヘッダー名と値のテンプレートを指定できるようにしたい。

```
default_auth_header_template =  "x-my-auth-header=$token"
```
