### ISSUE TITLE
[compat] キャッシュの扱い

### ISSUE THREAD

**Issue by cm-kazup0n** [cm-kazup0n/aurl-rust#4]
仕様から諸々考える

**Comment by komuro-hiraku** [comment]
- キャッシュの永続化する時のデータ構造
- キャッシュ更新、破棄のタイミング
- 有効期限があるやつは期限つきでキャッシュ
- ないやつはデフォルト値を期限にしてキャッシュする
- データ構造
  - token: アクセストークン
  - ttl: 有効期限のエポックms
  - etc...
